version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto
    expose:
      - 1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
  test:
    build: .
    expose:
      - 4840
    volumes:
      - .:/work
    depends_on:
      - mosquitto